// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceProvider.Data.Contexts;

#nullable disable

namespace ServiceProvider.Data.Migrations
{
    [DbContext(typeof(ServiceProviderContext))]
    [Migration("20251130215909_addedservicelistingmodel")]
    partial class addedservicelistingmodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sp")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CancelledAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ServiceListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceListingId");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("SP_Booking", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SP_Category", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Constituency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConstituencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("CountyId");

                    b.ToTable("SP_Constituency", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.County", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.ToTable("SP_County", "sp");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc0aa0a7-2773-4975-9168-f023d32ea1fa"),
                            CountyName = "MOMBASA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("659fb76c-ccf6-400d-b402-dfc7bc4914db"),
                            CountyName = "KWALE",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("333bccd2-e9d2-488e-865e-30747007e8ab"),
                            CountyName = "KILIFI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9e70507f-36e1-4dc4-91cd-56da976dd6ad"),
                            CountyName = "TANA RIVER",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5fd40543-0f23-41d3-a27a-153722619144"),
                            CountyName = "LAMU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("45d5300c-06e8-461e-875b-e534d4ac5fdb"),
                            CountyName = "TAITA TAVETA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("480b37bf-ddaa-441f-a85e-51cf6bc25009"),
                            CountyName = "GARISSA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("05e42c00-0d43-4f8c-b298-6197b59a7c5a"),
                            CountyName = "WAJIR",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5dca870b-b1bd-4864-8a1f-1ec3c45c4fed"),
                            CountyName = "MANDERA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("260fbbe6-4b60-497b-9d87-5be144a26744"),
                            CountyName = "MARSABIT",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("faa47f9a-6939-4a9c-a248-81ebbf3a21ca"),
                            CountyName = "ISIOLO",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2f78708-619c-460c-b6fa-54bc3195bc25"),
                            CountyName = "MERU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aacb62ee-3d24-486c-a97b-2109bead3d84"),
                            CountyName = "THARAKA-NITHI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4bf38bdc-8991-4085-a797-83fc8f29306d"),
                            CountyName = "EMBU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ccf5cc04-9bf0-479d-aa99-f1b22b189ce0"),
                            CountyName = "KITUI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c779d704-8ae4-42ac-bdb0-b68b36b92e8e"),
                            CountyName = "MACHAKOS",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2d6d3e4-77eb-4e20-90d0-514cd8ea7e60"),
                            CountyName = "MAKUENI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5980635a-d32f-45f6-902f-89e8b3f52b25"),
                            CountyName = "NYANDARUA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5ac861e4-c35a-4aec-a595-140abf57615e"),
                            CountyName = "NYERI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("88fa40c0-3a9d-4781-8ddf-e42ba55d8d87"),
                            CountyName = "KIRINYAGA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f9b44c46-1901-4d6d-b0ca-058ee2aeaaa5"),
                            CountyName = "MURANG'A",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9252581a-26cd-4dd4-8598-8ad606833bbb"),
                            CountyName = "KIAMBU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("fc5a5586-023b-4c85-b9d5-bc32d12c1749"),
                            CountyName = "TURKANA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("32c68bda-8bfa-4e8a-bf4e-f3ee4ec7524a"),
                            CountyName = "WEST POKOT",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c1c3b126-38e0-49cb-8ff9-14e78af8590a"),
                            CountyName = "SAMBURU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0c92ad83-1cae-4564-9745-19bd589dc0ec"),
                            CountyName = "TRANS NZOIA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c8c5136c-da3e-4712-aa3e-56d514480fc6"),
                            CountyName = "UASIN GISHU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aff8c339-ee07-4287-b6c0-a38bec68ae3e"),
                            CountyName = "ELGEYO/MARAKWET",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e924bfdd-acb6-45d3-a784-e4bdf4f1918d"),
                            CountyName = "NANDI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7e849cf0-01f2-4f4d-ba21-48bac890fcd3"),
                            CountyName = "BARINGO",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5cc690b1-c1e6-4943-9f83-33b3eb526d51"),
                            CountyName = "LAIKIPIA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7cb2a86a-000c-491e-b533-ffc4f0afd58a"),
                            CountyName = "NAKURU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0f6bfba1-9147-495c-91de-607be4ce8d98"),
                            CountyName = "NAROK",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("94f2f4c5-ddf6-48f1-bdb5-902c6954eefd"),
                            CountyName = "KAJIADO",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("435f9701-8099-431d-973c-92fac09b8138"),
                            CountyName = "KERICHO",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("31952a88-8a7f-4bee-a13d-dbb6e1f16e60"),
                            CountyName = "BOMET",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f3c7e49b-511a-421b-a20b-1f2abe98f68a"),
                            CountyName = "KAKAMEGA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a13a2ada-21f7-4ba1-b248-5123bb1ea245"),
                            CountyName = "VIHIGA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5adf4af9-33e4-4e94-b6d5-52031ad18926"),
                            CountyName = "BUNGOMA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("846ee2dc-5796-45fa-89b7-8ba56840905c"),
                            CountyName = "BUSIA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("27a81b5e-79d3-413e-84a5-a9e1a1e4bcad"),
                            CountyName = "SIAYA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ee847901-b1d6-4cfd-bba4-204c64745298"),
                            CountyName = "KISUMU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9eadb99e-ed71-4e89-a313-de7d6849b690"),
                            CountyName = "HOMA BAY",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("809fb497-8ea5-41cf-9947-52252b9d4a0d"),
                            CountyName = "MIGORI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4b16ba9a-f1fd-4021-95dc-0f62838b147c"),
                            CountyName = "KISII",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("74c3647b-1ec0-4d43-a5ec-cd741efc8b89"),
                            CountyName = "NYAMIRA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("1375ea45-3e76-4e59-8aa4-e00223562079"),
                            CountyName = "NAIROBI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.CustomService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SP_CustomService", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.EntityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActiveUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ChangeTrigger")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("ChangeType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("LoggedInUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoggedInUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrimaryKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReviewId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActiveUserId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("ReviewId1");

                    b.HasIndex("UserId");

                    b.ToTable("SP_EntityLog", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActiveUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("LoggedInUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoggedInUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReviewId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveUserId");

                    b.HasIndex("LoggedInUserId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("ReviewId1");

                    b.ToTable("SP_ErrorLog", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SP_Location", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.LoginLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Reason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("SP_LoginLog", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Medias.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SP_Media", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<byte>("Currency")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SP_Payment", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SP_Permission", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("BillingCycle")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(19,4)");

                    b.Property<byte>("Time")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("SP_Plan", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ProviderLocations", b =>
                {
                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceProviderId", "LocationId");

                    b.ToTable("SP_ProviderLocations", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ProviderServices", b =>
                {
                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceListingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceProviderId", "ServiceId");

                    b.ToTable("SP_ProviderServices", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("ServiceListingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceListingId");

                    b.ToTable("SP_Review", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SP_Role", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("SP_RolePermission", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ServiceProviderEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ServiceProviderEntityId");

                    b.ToTable("SP_Service", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ServiceListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("BasePrice")
                        .HasColumnType("float");

                    b.Property<Guid?>("CustomServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("PaymentMode")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomServiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("SP_ServiceListing", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ServiceProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("SP_ServiceProviderEntity", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("RenewalType")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .IsUnique();

                    b.HasIndex("ServiceProviderId")
                        .IsUnique();

                    b.ToTable("SP_Subscription", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("SP_User", "sp");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcfaff46-e2c3-4b3d-ba44-dfe86b9dfcd3"),
                            DateCreated = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@none.com",
                            FirstName = "ADM",
                            IsActive = true,
                            LastName = "Admin",
                            Password = "AdminPassword123!"
                        },
                        new
                        {
                            Id = new Guid("17ff54a6-9d9a-45dc-95ea-10b68b9e6378"),
                            DateCreated = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sam@none.com",
                            FirstName = "Sam",
                            IsActive = true,
                            LastName = "Admin",
                            Password = "AdminPassword123!"
                        },
                        new
                        {
                            Id = new Guid("4315515f-9932-49b7-a01d-7261047ed1c9"),
                            DateCreated = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dorcis@none.com",
                            FirstName = "Dorcis",
                            IsActive = true,
                            LastName = "Admin",
                            Password = "AdminPassword123!"
                        });
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("SP_UserPermission", "sp");
                });

            modelBuilder.Entity("Booking", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.ServiceListing", "ServiceListing")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceProvider.Core.Models.ServiceProviderEntity", "ServiceProvider")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceProvider.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ServiceListing");

                    b.Navigation("ServiceProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Constituency", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.County", "County")
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.EntityLog", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.User", "ActiveUser")
                        .WithMany("EntityLogsActive")
                        .HasForeignKey("ActiveUserId");

                    b.HasOne("ServiceProvider.Core.Models.Review", null)
                        .WithMany("EntityLogsActive")
                        .HasForeignKey("ReviewId");

                    b.HasOne("ServiceProvider.Core.Models.Review", null)
                        .WithMany("EntityLogsLoggedIn")
                        .HasForeignKey("ReviewId1");

                    b.HasOne("ServiceProvider.Core.Models.User", null)
                        .WithMany("EntityLogsLoggedIn")
                        .HasForeignKey("UserId");

                    b.Navigation("ActiveUser");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ErrorLog", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.User", "ActiveUser")
                        .WithMany("ErrorLogsActive")
                        .HasForeignKey("ActiveUserId");

                    b.HasOne("ServiceProvider.Core.Models.User", "LoggedInUser")
                        .WithMany("ErrorLogsLoggedIn")
                        .HasForeignKey("LoggedInUserId");

                    b.HasOne("ServiceProvider.Core.Models.Review", null)
                        .WithMany("ErrorLogsActive")
                        .HasForeignKey("ReviewId");

                    b.HasOne("ServiceProvider.Core.Models.Review", null)
                        .WithMany("ErrorLogsLoggedIn")
                        .HasForeignKey("ReviewId1");

                    b.Navigation("ActiveUser");

                    b.Navigation("LoggedInUser");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.LoginLog", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.Review", null)
                        .WithMany("LoginLogs")
                        .HasForeignKey("ReviewId");

                    b.HasOne("ServiceProvider.Core.Models.User", "User")
                        .WithMany("LoginLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Review", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ServiceProvider.Core.Models.ServiceListing", "ServiceListing")
                        .WithMany("Reviews")
                        .HasForeignKey("ServiceListingId");

                    b.Navigation("ServiceListing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.RolePermission", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId");

                    b.HasOne("ServiceProvider.Core.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Service", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceProvider.Core.Models.ServiceProviderEntity", null)
                        .WithMany("Services")
                        .HasForeignKey("ServiceProviderEntityId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ServiceListing", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.CustomService", "CustomService")
                        .WithMany()
                        .HasForeignKey("CustomServiceId");

                    b.HasOne("ServiceProvider.Core.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceProvider.Core.Models.ServiceProviderEntity", "ServiceProvider")
                        .WithMany("ServiceListings")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomService");

                    b.Navigation("Service");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Subscription", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.Plan", "Plan")
                        .WithOne("Subscription")
                        .HasForeignKey("ServiceProvider.Core.Models.Subscription", "PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceProvider.Core.Models.ServiceProviderEntity", "ServiceProvider")
                        .WithOne("Subscription")
                        .HasForeignKey("ServiceProvider.Core.Models.Subscription", "ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.User", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.UserPermission", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceProvider.Core.Models.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Plan", b =>
                {
                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Review", b =>
                {
                    b.Navigation("EntityLogsActive");

                    b.Navigation("EntityLogsLoggedIn");

                    b.Navigation("ErrorLogsActive");

                    b.Navigation("ErrorLogsLoggedIn");

                    b.Navigation("LoginLogs");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ServiceListing", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ServiceProviderEntity", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ServiceListings");

                    b.Navigation("Services");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.User", b =>
                {
                    b.Navigation("EntityLogsActive");

                    b.Navigation("EntityLogsLoggedIn");

                    b.Navigation("ErrorLogsActive");

                    b.Navigation("ErrorLogsLoggedIn");

                    b.Navigation("LoginLogs");

                    b.Navigation("Permissions");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
