// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceProvider.Data.Contexts;

#nullable disable

namespace ServiceProvider.Data.Migrations
{
    [DbContext(typeof(ServiceProviderContext))]
    [Migration("20251130221802_addedplanId")]
    partial class addedplanId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sp")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CancelledAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ServiceListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceListingId");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("SP_Booking", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SP_Category", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Constituency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConstituencyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("CountyId");

                    b.ToTable("SP_Constituency", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.County", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.ToTable("SP_County", "sp");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8cbca1d3-3194-4178-92f3-5856a8a96e53"),
                            CountyName = "MOMBASA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5f038539-c58a-4a06-a4e2-aa9cc75fbbd4"),
                            CountyName = "KWALE",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9709b056-8fee-4682-9228-6f64a5a4b0e8"),
                            CountyName = "KILIFI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d6f942e1-35e2-4a93-a574-f73f06410841"),
                            CountyName = "TANA RIVER",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5d936779-e4ad-45f1-9ef4-fcd70c69fe0d"),
                            CountyName = "LAMU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8df45b8e-812f-41e1-b8d8-3fc34fd3b9f9"),
                            CountyName = "TAITA TAVETA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9191d222-4c59-45ac-8545-dd7f575e7902"),
                            CountyName = "GARISSA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b19c9109-8c4c-4f78-9053-608d57778608"),
                            CountyName = "WAJIR",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("dd6e6599-00b7-47ef-8d71-7f2b3f6be062"),
                            CountyName = "MANDERA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e13b945e-19b6-4ce6-a224-c76ea0c0618f"),
                            CountyName = "MARSABIT",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("74fea505-2c3d-4264-9add-24b50a030c50"),
                            CountyName = "ISIOLO",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("41545318-9674-42c8-84ac-d082f8fa96de"),
                            CountyName = "MERU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44a56200-9cf3-4855-8183-35d3070ff93c"),
                            CountyName = "THARAKA-NITHI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5eab3d8c-a8b0-4d47-a187-c8e7ee2ddc42"),
                            CountyName = "EMBU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a048cc59-0b84-4996-9f2e-41eb2f5b9c07"),
                            CountyName = "KITUI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a70f6e3d-708d-475e-95b3-b41295501d93"),
                            CountyName = "MACHAKOS",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2bdefdf6-8af8-452c-94a1-8ff8480279bd"),
                            CountyName = "MAKUENI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2113c64d-ec5b-4fed-9f5e-a921aaa08b74"),
                            CountyName = "NYANDARUA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("af4d9ede-23ee-45e2-b7b2-2036786dda14"),
                            CountyName = "NYERI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2b380f15-aded-44eb-ad8b-d5b44d14ef16"),
                            CountyName = "KIRINYAGA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("819572da-627e-418b-acda-c9a5cc3a4261"),
                            CountyName = "MURANG'A",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b9bac2b0-4620-4571-a9ec-c2790d9c9263"),
                            CountyName = "KIAMBU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("372d6161-dffd-4da6-927e-160b87619bfb"),
                            CountyName = "TURKANA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("df0a7535-cdae-44b6-901a-2c868b77b0d4"),
                            CountyName = "WEST POKOT",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("58d165f6-3d51-49f2-9aa7-e0d438a580bf"),
                            CountyName = "SAMBURU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4fd5fd7b-a680-4689-9caf-00e6f644b59d"),
                            CountyName = "TRANS NZOIA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("73c23f5e-3dbd-4cd7-9e29-5b9190db11d5"),
                            CountyName = "UASIN GISHU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3f1a9017-cab3-4727-9a63-ec41af45aad8"),
                            CountyName = "ELGEYO/MARAKWET",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3762ecb8-bd0f-4435-be15-09ee83da9b0e"),
                            CountyName = "NANDI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5f96c3b2-f1ca-4671-ae5f-20df01757d79"),
                            CountyName = "BARINGO",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e4cd5ab4-e0ad-47ce-bf1b-1543de844a63"),
                            CountyName = "LAIKIPIA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("09a7b4e7-c68d-42a4-9dd8-97cabaf36556"),
                            CountyName = "NAKURU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("67a5ce11-2ee8-4b07-ba14-e17ababcf1f6"),
                            CountyName = "NAROK",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("35296b42-87ac-461c-97ff-206aa371264d"),
                            CountyName = "KAJIADO",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c78ade45-4b1f-43cb-9c79-cbbf1606db01"),
                            CountyName = "KERICHO",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d521fd25-9d93-4f76-848d-09acecfa72d6"),
                            CountyName = "BOMET",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2c6b0c7-7342-4b2f-bd99-43f1d983d319"),
                            CountyName = "KAKAMEGA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a9ff2b81-9667-4b37-ac9d-7930462907ff"),
                            CountyName = "VIHIGA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("793d3d54-b005-4e8c-a758-dd65a0201277"),
                            CountyName = "BUNGOMA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9d9a54d3-aa13-4285-bac1-4480c1316cd4"),
                            CountyName = "BUSIA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e6330940-fa09-4fa1-b84e-155289f1733a"),
                            CountyName = "SIAYA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cf60bcc4-c626-4c4e-80ea-a7498ed37cae"),
                            CountyName = "KISUMU",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("67a9c041-9b03-4375-b45a-c35478ca50ee"),
                            CountyName = "HOMA BAY",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b1e14c99-f476-48ce-becb-c8abe7dad93b"),
                            CountyName = "MIGORI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c7d31fd4-a860-4992-bb89-0b1fae5365d4"),
                            CountyName = "KISII",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5cbbe34f-88f6-4790-b4cb-55c76a47cae6"),
                            CountyName = "NYAMIRA",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b5e127cf-4187-4ca9-b68d-8e10ad368680"),
                            CountyName = "NAIROBI",
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.CustomService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SP_CustomService", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.EntityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActiveUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ChangeTrigger")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("ChangeType")
                        .HasColumnType("tinyint");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("LoggedInUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoggedInUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PrimaryKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReviewId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActiveUserId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("ReviewId1");

                    b.HasIndex("UserId");

                    b.ToTable("SP_EntityLog", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActiveUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("LoggedInUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoggedInUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReviewId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveUserId");

                    b.HasIndex("LoggedInUserId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("ReviewId1");

                    b.ToTable("SP_ErrorLog", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SP_Location", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.LoginLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Reason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("SP_LoginLog", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Medias.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SP_Media", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<byte>("Currency")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SP_Payment", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SP_Permission", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("BillingCycle")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<byte>("IsActive")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(19,4)");

                    b.Property<byte>("Time")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("SP_Plan", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ProviderLocations", b =>
                {
                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceProviderId", "LocationId");

                    b.ToTable("SP_ProviderLocations", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ProviderServices", b =>
                {
                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceListingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServiceProviderId", "ServiceId");

                    b.ToTable("SP_ProviderServices", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid?>("ServiceListingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceListingId");

                    b.ToTable("SP_Review", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SP_Role", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("SP_RolePermission", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ServiceProviderEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ServiceProviderEntityId");

                    b.ToTable("SP_Service", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ServiceListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("BasePrice")
                        .HasColumnType("float");

                    b.Property<Guid?>("CustomServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("PaymentMode")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomServiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("SP_ServiceListing", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ServiceProviderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("SP_ServiceProviderEntity", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("RenewalType")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("ServiceProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PlanId")
                        .IsUnique();

                    b.HasIndex("ServiceProviderId")
                        .IsUnique();

                    b.ToTable("SP_Subscription", "sp");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("SP_User", "sp");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dcfaff46-e2c3-4b3d-ba44-dfe86b9dfcd3"),
                            DateCreated = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@none.com",
                            FirstName = "ADM",
                            IsActive = true,
                            LastName = "Admin",
                            Password = "AdminPassword123!"
                        },
                        new
                        {
                            Id = new Guid("17ff54a6-9d9a-45dc-95ea-10b68b9e6378"),
                            DateCreated = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sam@none.com",
                            FirstName = "Sam",
                            IsActive = true,
                            LastName = "Admin",
                            Password = "AdminPassword123!"
                        },
                        new
                        {
                            Id = new Guid("4315515f-9932-49b7-a01d-7261047ed1c9"),
                            DateCreated = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dorcis@none.com",
                            FirstName = "Dorcis",
                            IsActive = true,
                            LastName = "Admin",
                            Password = "AdminPassword123!"
                        });
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("SP_UserPermission", "sp");
                });

            modelBuilder.Entity("Booking", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.ServiceListing", "ServiceListing")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceProvider.Core.Models.ServiceProviderEntity", "ServiceProvider")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceProvider.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ServiceListing");

                    b.Navigation("ServiceProvider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Constituency", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.County", "County")
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.EntityLog", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.User", "ActiveUser")
                        .WithMany("EntityLogsActive")
                        .HasForeignKey("ActiveUserId");

                    b.HasOne("ServiceProvider.Core.Models.Review", null)
                        .WithMany("EntityLogsActive")
                        .HasForeignKey("ReviewId");

                    b.HasOne("ServiceProvider.Core.Models.Review", null)
                        .WithMany("EntityLogsLoggedIn")
                        .HasForeignKey("ReviewId1");

                    b.HasOne("ServiceProvider.Core.Models.User", null)
                        .WithMany("EntityLogsLoggedIn")
                        .HasForeignKey("UserId");

                    b.Navigation("ActiveUser");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ErrorLog", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.User", "ActiveUser")
                        .WithMany("ErrorLogsActive")
                        .HasForeignKey("ActiveUserId");

                    b.HasOne("ServiceProvider.Core.Models.User", "LoggedInUser")
                        .WithMany("ErrorLogsLoggedIn")
                        .HasForeignKey("LoggedInUserId");

                    b.HasOne("ServiceProvider.Core.Models.Review", null)
                        .WithMany("ErrorLogsActive")
                        .HasForeignKey("ReviewId");

                    b.HasOne("ServiceProvider.Core.Models.Review", null)
                        .WithMany("ErrorLogsLoggedIn")
                        .HasForeignKey("ReviewId1");

                    b.Navigation("ActiveUser");

                    b.Navigation("LoggedInUser");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.LoginLog", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.Review", null)
                        .WithMany("LoginLogs")
                        .HasForeignKey("ReviewId");

                    b.HasOne("ServiceProvider.Core.Models.User", "User")
                        .WithMany("LoginLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Review", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ServiceProvider.Core.Models.ServiceListing", "ServiceListing")
                        .WithMany("Reviews")
                        .HasForeignKey("ServiceListingId");

                    b.Navigation("ServiceListing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.RolePermission", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId");

                    b.HasOne("ServiceProvider.Core.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Service", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceProvider.Core.Models.ServiceProviderEntity", null)
                        .WithMany("Services")
                        .HasForeignKey("ServiceProviderEntityId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ServiceListing", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.CustomService", "CustomService")
                        .WithMany()
                        .HasForeignKey("CustomServiceId");

                    b.HasOne("ServiceProvider.Core.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceProvider.Core.Models.ServiceProviderEntity", "ServiceProvider")
                        .WithMany("ServiceListings")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomService");

                    b.Navigation("Service");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Subscription", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.Plan", "Plan")
                        .WithOne("Subscription")
                        .HasForeignKey("ServiceProvider.Core.Models.Subscription", "PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceProvider.Core.Models.ServiceProviderEntity", "ServiceProvider")
                        .WithOne("Subscription")
                        .HasForeignKey("ServiceProvider.Core.Models.Subscription", "ServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.User", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.UserPermission", b =>
                {
                    b.HasOne("ServiceProvider.Core.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceProvider.Core.Models.User", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Plan", b =>
                {
                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Review", b =>
                {
                    b.Navigation("EntityLogsActive");

                    b.Navigation("EntityLogsLoggedIn");

                    b.Navigation("ErrorLogsActive");

                    b.Navigation("ErrorLogsLoggedIn");

                    b.Navigation("LoginLogs");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ServiceListing", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.ServiceProviderEntity", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ServiceListings");

                    b.Navigation("Services");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("ServiceProvider.Core.Models.User", b =>
                {
                    b.Navigation("EntityLogsActive");

                    b.Navigation("EntityLogsLoggedIn");

                    b.Navigation("ErrorLogsActive");

                    b.Navigation("ErrorLogsLoggedIn");

                    b.Navigation("LoginLogs");

                    b.Navigation("Permissions");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
