name: Build and deploy ASP.Net Core app to Azure Web App - serviceprovider

env:
  AZURE_WEBAPP_NAME: serviceprovider   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0' 
  RGNAME: serviceprovider-dev  #serviceprovider

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Set up Azure CLI
        run: az --version

      - name: Orchestrate web server
        run: | #az deployment sub create --name rumSubDeployment --location eastus2
          az deployment sub create --name ${{env.RGNAME}} --template-file ./Infrastructure/Main.bicep -p ./Infrastructure/Parameters/Parameters-dev.json

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/publish

      - name: Deploy web app to Azure
        run: | 
          Compress-Archive -Force ${{env.DOTNET_ROOT}}/publish/* publish.zip
          az webapp deployment source config-zip -g ${{env.RGNAME}} -n ${{env.AZURE_WEBAPP_NAME}} --src publish.zip
          echo "The Web App URL is https://${{env.AZURE_WEBAPP_NAME}}.azurewebsites.net" >> $GITHUB_ENV
